"""add expense tables

Revision ID: 7b168dd2c3d1
Revises: 24b921f41e3b
Create Date: 2026-07-31 19:52:00.932894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b168dd2c3d1'
down_revision: Union[str, None] = '24b921f41e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID，NULL 表示一级分类'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='层级：1 / 2 / 3'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重，越小越靠前'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='修改时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='金额（元），> 0'),
    sa.Column('category_l1', sa.String(length=50), nullable=False, comment='一级分类名称（冗余）'),
    sa.Column('category_l2', sa.String(length=50), nullable=False, comment='二级分类名称（冗余）'),
    sa.Column('category_l3', sa.String(length=50), nullable=False, comment='三级分类名称（冗余）'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('expense_date', sa.Date(), nullable=False, comment='支出日期'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='修改时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 支出表索引
    op.create_index('ix_expenses_user_date', 'expenses', ['user_id', 'expense_date'])
    op.create_index('ix_expenses_user_l1_date', 'expenses', ['user_id', 'category_l1', 'expense_date'])
    op.create_index('ix_expenses_user_l2_date', 'expenses', ['user_id', 'category_l1', 'category_l2', 'expense_date'])
    # 分类表索引
    op.create_index('ix_expense_categories_user_parent', 'expense_categories', ['user_id', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_categories_user_parent', table_name='expense_categories')
    op.drop_index('ix_expenses_user_l2_date', table_name='expenses')
    op.drop_index('ix_expenses_user_l1_date', table_name='expenses')
    op.drop_index('ix_expenses_user_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
