"""initial schema

Revision ID: ff245e876ff9
Revises: 
Create Date: 2026-07-30 09:12:26.146029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff245e876ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希（bcrypt）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='车辆名称（如 KPT400）'),
    sa.Column('plate', sa.String(length=20), nullable=True, comment='车牌号'),
    sa.Column('initial_mileage', sa.Numeric(precision=10, scale=1), nullable=False, comment='初始里程（首次记录时的里程）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='所属用户'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='所属车辆'),
    sa.Column('mileage', sa.Numeric(precision=10, scale=1), nullable=False, comment='当前里程表读数 (km)'),
    sa.Column('fuel_volume', sa.Numeric(precision=10, scale=2), nullable=False, comment='加油量 (L)'),
    sa.Column('fuel_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='加油金额 (元)'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='单价 = 金额/油量'),
    sa.Column('is_full_tank', sa.Boolean(), nullable=True, comment='是否加满'),
    sa.Column('is_baseline', sa.Boolean(), nullable=True, comment='基线记录（首次加油，不计算油耗）'),
    sa.Column('fuel_consumption', sa.Numeric(precision=5, scale=2), nullable=True, comment='百公里油耗 (L/100km)'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('record_date', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_records')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
